### ISSUE TITLE
wasm2c does nothing at all

### ISSUE THREAD

**Issue by Photosounder** [WebAssembly/wabt#2323] opened 2023-11-08 11:05 UTC
wasm2c.exe on Windows 10, ran through MSys2, does nothing at all since wabt 1.0.33. Nothing in stdout, nothing in output files, it appears to just not do anything. Only wabt 1.0.32 works correctly.

The following are tested using the last 3 releases named `wabt-1.0.3x-windows.tar.gz`

```
user@DESKTOP-AP5KGUV ~/home/wasm_app
$/home/lib/wabt-1.0.32/bin/wasm2c.exe
wasm2c: expected filename argument.
Try '--help' for more information.

user@DESKTOP-AP5KGUV ~/home/wasm_app
$/home/lib/wabt-1.0.33/bin/wasm2c.exe

user@DESKTOP-AP5KGUV ~/home/wasm_app
$/home/lib/wabt-1.0.34/bin/wasm2c.exe

user@DESKTOP-AP5KGUV ~/home/wasm_app
$
```

All the other utilities appear to work correctly in wabt 1.0.34:
```
user@DESKTOP-AP5KGUV ~/home/wasm_app
$/home/lib/wabt-1.0.34/bin/wasm-decompile.exe
wasm-decompile: expected filename argument.
Try '--help' for more information.

user@DESKTOP-AP5KGUV ~/home/wasm_app
$/home/lib/wabt-1.0.34/bin/wasm-objdump.exe
wasm-objdump: expected filename argument.
Try '--help' for more information.

user@DESKTOP-AP5KGUV ~/home/wasm_app
$/home/lib/wabt-1.0.34/bin/wasm-strip.exe
wasm-strip: expected filename argument.
Try '--help' for more information.

user@DESKTOP-AP5KGUV ~/home/wasm_app
$/home/lib/wabt-1.0.34/bin/wasm2c.exe

user@DESKTOP-AP5KGUV ~/home/wasm_app
$/home/lib/wabt-1.0.34/bin/wasm-interp.exe
wasm-interp: expected filename argument.
Try '--help' for more information.

user@DESKTOP-AP5KGUV ~/home/wasm_app
$/home/lib/wabt-1.0.34/bin/wasm-stats.exe
wasm-stats: expected filename argument.
Try '--help' for more information.

user@DESKTOP-AP5KGUV ~/home/wasm_app
$/home/lib/wabt-1.0.34/bin/wasm-validate.exe
wasm-validate: expected filename argument.
Try '--help' for more information.

user@DESKTOP-AP5KGUV ~/home/wasm_app
$/home/lib/wabt-1.0.34/bin/wasm2wat.exe
wasm2wat: expected filename argument.
Try '--help' for more information.
```

**Comment by keithw** [comment] 2023-11-10 03:22
Hmm... "it works in CI." If you can bisect this, that might be helpful, or if other Windows users are affected, maybe you can help each other try to figure out what's happening. I am tempted to have us stop publishing binary releases on GitHub since they seem to cause a lot of trouble (and it's not really our core competency -- seems like like Homebrew/Debian/the Windows equivalent are probably better at publishing binary releases for all these architectures than we are).

Not saying it's not a bug somehow, just that beyond building and testing in CI, I suspect we're not going to be at our best trying to debug an issue with the binary Windows release. (Does it work if you compile from source? Or does the Linux release work for you in WSL?)

**Comment by keithw** [comment] 2023-12-05 01:25
Closing as dormant. Please feel free to respond and we can reopen (or if anybody else is having this problem, please also speak up).

**Closed by keithw** 2023-12-05 01:25 UTC

**Comment by Photosounder** [comment] 2023-12-05 10:19
Did you even try running the program yourself? If you break something on Windows and aren't interested in investigating it then you're effectively dropping Windows support.

**Comment by keithw** [comment] 2023-12-05 18:36
No -- my only access to Windows is via the GitHub CI environment. I'm not sure we "support" any platform per se, but if you respond to some of the questions in my original reply we can help investigate. AFAIK wasm2c does have a reasonable userbase on Windows (probably mostly people building Firefox) and we aven't heard this complaint from anybody else so far; it would be useful to know how broadly Windows users/configurations are affected.
