### ISSUE TITLE
TARGET_ARCH sniffing doesn't handle arm64 on OSX

### ISSUE THREAD

**Issue by steven-johnson** [WebAssembly/wabt#1709] opened 2021-09-15 20:42 UTC
When compiling on an arm64 Mac, configuring the build produces the warning:

```
CMake Warning at CMakeLists.txt:197 (message):
  Unknown target architecture!
```

This is a common enough architecture now that it should be handled without warning.

**Comment by rathann** [comment] 2022-02-07 22:05
Duplicate of #1688 .

**Comment by keithw** [comment] 2022-08-25 21:47
Closing as duplicate of #1688

**Closed by keithw** 2022-08-25 21:47 UTC
