### ISSUE TITLE
Lost Data Count Section when encoding from WAT in `wast2json` tool

### ISSUE THREAD

**Issue by q82419** [WebAssembly/wabt#1959] opened 2022-08-14 01:02 UTC
Hi, I'm using the `wast2json` tool to generate the test suites.
In the spec test suites [L190-L192](https://github.com/WebAssembly/spec/blob/main/test/core/memory_init.wast#L190-L192) and [L227-L229](https://github.com/WebAssembly/spec/blob/main/test/core/memory_init.wast#L227-L229), authought they are the `assert_invalid` cases, but the datacount section after generating is lost.

Take the following `wast` (named as `test.wast`) as example:

```
(assert_invalid
   (module
     (func (export "test")
       (data.drop 0)))
   "unknown data segment")
```

After the following command:

```
$ ./wast2json test.wast
```

The files are:

```
.
├── test.0.wasm
├── test.json
└── test.wast
```

I found that after the version `1.0.26`, the `test.0.wasm` in binary will be:

```
;; WASM magic and version
00 61 73 6D 01 00 00 00
;; Type section
01 04 01 60 00 00
;; Function section
03 02 01 00
;; Export section
07 08 01 04 74 65 73 74 00 00
;; Lost Data Count section here
;; Code section
0A 07 01 05 00 FC 09 00 0B
```

But the version `1.0.24`, the command:

```
$ ./wast2json --enable-bulk-memory --enable-reference-types test.wast
```

The `test.0.wasm` in binary will be:

```
;; WASM magic and version
00 61 73 6D 01 00 00 00
;; Type section
01 04 01 60 00 00
;; Function section
03 02 01 00
;; Export section
07 08 01 04 74 65 73 74 00 00
;; Data Count section
0C 01 00
;; Code section
0A 07 01 05 00 FC 09 00 0B
```

According to the [spec](https://webassembly.github.io/spec/core/binary/modules.html#data-count-section), the data count section is used to simplify single-pass validation and the `memory.init` and `data.drop` instructions need to use it for checking the data segment index.
Although this case is an invalid module, I think the data count section should be added when converting this WAST with the `wast2json` tool?

Thanks.

**Comment by keithw** [comment] 2022-08-16 20:04
The binary writer removes the DataCount section if the module doesn't have any data segments (#1312). This seems arguably correct to me? (At least, it seems like it could only make a difference with invalid modules...)

**Comment by q82419** [comment] 2022-08-24 11:48
For the `wast2json` tool, I think it's propper to add the data count section with any `data.drop` or `memory.init` instructions appears in function bodies or the data segment exists, but not only the existence of data segments?
After all, the data count section is needed because of these instructions, and only these 2 instructions will access the data instance index.

In the case of the legal modules, therefore the data count section will not be omitted neither these instructions nor the data section exists.
In this special invalid module case, the data count section can be omitted because these instructions appeared.

**Comment by keithw** [comment] 2022-08-24 15:50
I don't necessarily disagree, but, try making the change and you'll see why this would involve a bunch of churn. In #1727, it looks like we expressly made the opposite choice with eyes open. :-/

**Comment by keithw** [comment] 2022-09-01 14:28
Closing this issue for now as "provisionally working as intended," but please do feel free to reopen or submit a contrary PR (with necessary changes to test output) and we can continue the discussion.

**Closed by keithw** 2022-09-01 14:28 UTC
