### ISSUE TITLE
Many floating-point errors on i386

### ISSUE THREAD

**Issue by alexreinking** [WebAssembly/wabt#1973] opened 2022-08-27 22:29 UTC
When running the full test suite on i386, many floating-point-related failures occur. The test summary is reproduced below.

```
**** FAILED ******************************************************************
- test/spec/float_exprs.txt
    /ws/build/spectest-interp out/test/spec/float_exprs/float_exprs.json
- test/spec/float_misc.txt
    /ws/build/spectest-interp out/test/spec/float_misc/float_misc.json
- test/spec/local_tee.txt
    /ws/build/spectest-interp out/test/spec/local_tee/local_tee.json
- test/spec/simd_f32x4_arith.txt
    /ws/build/spectest-interp out/test/spec/simd_f32x4_arith/simd_f32x4_arith.json
- test/spec/simd_f32x4_pmin_pmax.txt
    /ws/build/spectest-interp out/test/spec/simd_f32x4_pmin_pmax/simd_f32x4_pmin_pmax.json
- test/spec/simd_f64x2_arith.txt
    /ws/build/spectest-interp out/test/spec/simd_f64x2_arith/simd_f64x2_arith.json
- test/spec/simd_f64x2_pmin_pmax.txt
    /ws/build/spectest-interp out/test/spec/simd_f64x2_pmin_pmax/simd_f64x2_pmin_pmax.json
- test/wasm2c/old-spec/select.txt
    /usr/bin/python3 /ws/test/run-spec-wasm2c.py out/test/wasm2c/old-spec/select.txt --bindir=/ws/build --no-error-cmdline -o out/test/wasm2c/old-spec/select
- test/wasm2c/spec/const.txt
    TIMEOUT
- test/wasm2c/spec/conversions.txt
    /usr/bin/python3 /ws/test/run-spec-wasm2c.py out/test/wasm2c/spec/conversions.wast --bindir=/ws/build --no-error-cmdline -o out/test/wasm2c/spec/conversions
- test/wasm2c/spec/float_exprs.txt
    /usr/bin/python3 /ws/test/run-spec-wasm2c.py out/test/wasm2c/spec/float_exprs.wast --bindir=/ws/build --no-error-cmdline -o out/test/wasm2c/spec/float_exprs
- test/wasm2c/spec/float_memory.txt
    /usr/bin/python3 /ws/test/run-spec-wasm2c.py out/test/wasm2c/spec/float_memory.wast --bindir=/ws/build --no-error-cmdline -o out/test/wasm2c/spec/float_memory
- test/wasm2c/spec/float_misc.txt
    /usr/bin/python3 /ws/test/run-spec-wasm2c.py out/test/wasm2c/spec/float_misc.wast --bindir=/ws/build --no-error-cmdline -o out/test/wasm2c/spec/float_misc
- test/wasm2c/spec/local_tee.txt
    /usr/bin/python3 /ws/test/run-spec-wasm2c.py out/test/wasm2c/spec/local_tee.wast --bindir=/ws/build --no-error-cmdline -o out/test/wasm2c/spec/local_tee
```

See the following GHA logs for full details: https://github.com/WebAssembly/wabt/runs/8053046874?check_suite_focus=true

**Comment by rathann** [comment] 2022-11-16 14:54
Duplicate of #1044 ?

**Comment by keithw** [comment] 2023-01-08 22:06
Duplicate of #1044

**Closed by keithw** 2023-01-08 22:06 UTC
