### ISSUE TITLE
000002c: error: invalid section code: 12

### ISSUE THREAD

**Issue by xhorak** [WebAssembly/wabt#1955] opened 2022-08-11 14:44 UTC
The `wasm2wat` works fine, but `wasm2c` returns:
`000002c: error: invalid section code: 12`
Full output:
wasm2wat:
```
(module
  (import "env" "__linear_memory" (memory (;0;) 1))
  (data $_ZN5woff210kKnownTagsE (i32.const 0) "pamcdaehaehhxtmhpxameman2/SOtsop tvcmgpffylgacolperp FFCGROVTDBECLBEpsagxmdhnrekHSTLTLCPXMDVaehvxtmvESABFEDGSOPGBUSGCSBEFTSJHTAMTDBCCLBCRLOCLAPC GVSxibstncaravatadbcolbnlsbravccsdftaefxtmfravfravgytshtsujracltromxromdbpoporpkartfpaZfliStalGcolGtaeFlliS"))
```

```
wasm2c -v table_tags.wasm
BeginModule(version: 1)
  BeginImportSection(24)
    OnImportCount(1)
    OnImport(index: 0, kind: memory, module: "env", field: "__linear_memory")
    OnImportMemory(import_index: 0, memory_index: 0, initial: 1)
  EndImportSection
000002c: error: invalid section code: 12
```
What could be the problem here?

**Comment by kripken** [comment] 2022-08-11 15:04
Section 12 is "DataCount", which I guess wasm2c does not support yet. That section is emitted in binaries that use bulk memory, and in wasm object files. (For wasm object files, you can link them using wasm-ld to a proper wasm executable before running them in wasm2c.)

**Comment by keithw** [comment] 2022-08-11 15:48
I can't seem to reproduce this error using the tip-of-tree tools. What version of wasm2wat and wasm2c are you using? I tried and it seems to work as intended:
```sh
$ cat > /tmp/mod.wat
(module
  (import "env" "__linear_memory" (memory (;0;) 1))
  (data $_ZN5woff210kKnownTagsE (i32.const 0) "pamcdaehaehhxtmhpxameman2/SOtsop tvcmgpffylgacolperp FFCGROVTDBECLBEpsagxmdhnrekHSTLTLCPXMDVaehvxtmvESABFEDGSOPGBUSGCSBEFTSJHTAMTDBCCLBCRLOCLAPC GVSxibstncaravatadbcolbnlsbravccsdftaefxtmfravfravgytshtsujracltromxromdbpoporpkartfpaZfliStalGcolGtaeFlliS"))
$ ./bin/wat2wasm /tmp/mod.wat -o /tmp/mod.wasm
$ ./bin/wasm2c /tmp/mod.wasm -o /tmp/mod.c
$ cat /tmp/mod.c
[...]
static const u8 data_segment_data_0[] = {
  0x70, 0x61, 0x6d, 0x63, 0x64, 0x61, 0x65, 0x68, 0x61, 0x65, 0x68, 0x68, 
[...]
};

static void init_memory(void) {
  LOAD_DATA((*Z_envZ___linear_memory), 0u, data_segment_data_0, 252);
}
```

FWIW, if you do end up needing bulk-memory support in wasm2c, there is a pending PR that provides this (#1877) that you are welcome to try.

**Comment by keithw** [comment] 2022-08-14 23:53
(Closing as answered.)

**Closed by keithw** 2022-08-14 23:53 UTC
