### ISSUE TITLE
GC supporting 

### ISSUE THREAD

**Issue by lum1n0us** [WebAssembly/wabt#1759] opened 2021-11-11 01:50 UTC
May I ask the supporting plan about the latest [GC MVP](https://github.com/WebAssembly/gc/blob/master/proposals/gc/MVP.md)?  The [GC branch](https://github.com/WebAssembly/wabt/tree/gc) hasn't been updated for a long time.

**Comment by sbc100** [comment] 2022-03-13 22:54
I think it would be great to get GC support in wabt, but I don't know of anyone actively working on it. 

Closing as duplicate of #1257.. lets continue any discussion there.

**Closed by sbc100** 2022-03-13 22:54 UTC
