### ISSUE TITLE
Build fails on FreeBSD

### ISSUE THREAD

**Issue by benlaurie** [WebAssembly/wabt#1149] opened 2019-08-29 10:08 UTC
```
% gmake test
gmake --no-print-directory -C out/clang/Debug/ run-tests
[ 62%] Built target wabt
[ 65%] Built target wast2json
[ 68%] Built target wasm-validate
[ 71%] Built target wasm-interp
[ 74%] Built target wasm-strip
[ 77%] Built target wat-desugar
[ 80%] Built target spectest-interp
[ 83%] Built target wat2wasm
[ 87%] Built target wasm-opcodecnt
[ 92%] Built target wasm2c
[ 96%] Built target wasm-objdump
[100%] Built target wasm2wat
/bin/sh: /home/ben/git-work/wabt/out/clang/Debug/wabt-unittests: not found
gmake[4]: *** [CMakeFiles/run-tests.dir/build.make:67: CMakeFiles/run-tests] Error 127
gmake[3]: *** [CMakeFiles/Makefile2:344: CMakeFiles/run-tests.dir/all] Error 2
gmake[2]: *** [CMakeFiles/Makefile2:351: CMakeFiles/run-tests.dir/rule] Error 2
gmake[1]: *** [Makefile:255: run-tests] Error 2
gmake: *** [Makefile:178: test-clang-debug] Error 2
```

Running ```cd out/clang/Debug/ && gmake wabt-unittests``` fixes it.

This is using 97bd353df98dfea72f1d7d06b4d087b508a4c37a.

**Comment by zach** [comment] 2019-08-31 03:54
Just tried this out using 97bd353df98dfea72f1d7d06b4d087b508a4c37a on FreeBSD 12.0 (12.0-RELEASE-p10) and `gmake` followed by `gmake debug` worked fine for me.

`gmake` produced this output and `out/clang/Debug/wabt-unittests` was present afterwards:
```
Scanning dependencies of target wabt-unittests
[ 78%] Building CXX object CMakeFiles/wabt-unittests.dir/src/test-binary-reader.cc.o
[ 79%] Building CXX object CMakeFiles/wabt-unittests.dir/src/test-circular-array.cc.o
[ 80%] Building CXX object CMakeFiles/wabt-unittests.dir/src/test-interp.cc.o
[ 82%] Building CXX object CMakeFiles/wabt-unittests.dir/src/test-intrusive-list.cc.o
[ 83%] Building CXX object CMakeFiles/wabt-unittests.dir/src/test-literal.cc.o
[ 84%] Building CXX object CMakeFiles/wabt-unittests.dir/src/test-option-parser.cc.o
[ 85%] Building CXX object CMakeFiles/wabt-unittests.dir/src/test-string-view.cc.o
[ 86%] Building CXX object CMakeFiles/wabt-unittests.dir/src/test-filenames.cc.o
[ 88%] Building CXX object CMakeFiles/wabt-unittests.dir/src/test-utf8.cc.o
[ 89%] Building CXX object CMakeFiles/wabt-unittests.dir/src/test-wast-parser.cc.o
[ 90%] Linking CXX executable wabt-unittests
[ 90%] Built target wabt-unittests
```

Then running `gmake test` went off without a hitch:
```
$ gmake test
gmake --no-print-directory -C out/clang/Debug/ run-tests
[ 62%] Built target wabt
[ 65%] Built target wast2json
[ 68%] Built target wasm-validate
[ 71%] Built target wasm-interp
[ 74%] Built target wasm-strip
[ 77%] Built target wat-desugar
[ 80%] Built target spectest-interp
[ 83%] Built target wat2wasm
[ 87%] Built target wasm-opcodecnt
[ 92%] Built target wasm2c
[ 96%] Built target wasm-objdump
[100%] Built target wasm2wat
Scanning dependencies of target run-tests
Running main() from gtest_main.cc
[==========] Running 172 tests from 20 test cases.
[----------] Global test environment set-up.
``` (etc.)

Not sure where things went wrong for you. Did there seem to be any problem building `wabt-unittests` on the initial `gmake` invocation?

**Comment by benlaurie** [comment] 2019-08-31 10:47
I did not run `gmake` first, just `gmake test` - surely `test` should build its prerequisites? It builds everything else (you can see in your output it also didn't build `wabt-unittests`).

If I run `gmake` first as you did, then indeed it works fine.

Its also a little puzzling that `gmake test` rebuilds things that `gmake` already built...

**Comment by sbc100** [comment] 2019-09-04 00:45
This looks like a dependency issue in the CMake file but its odd then that we've not seen it before.  Internally I build with high parallelism which normally shakes out such issues (The CI does too).

Is this reproducible for you?    Is it reproducible if you switch to ninja as the cmake generator (USE_NINJA=1 enabled this in the top level Makefile).

**Comment by binji** [comment] 2019-09-12 06:05
I was able to repro this issue, it seems to be just a missing dependency in the CMakeLists file. I don't think we've seen it before perhaps because most people don't run `make test`?

In any case, I've added a fix here: https://github.com/WebAssembly/wabt/pull/1157

**Comment by binji** [comment] 2019-09-25 20:25
Should be fixed now. I'll close, but please reopen if you still see the problem.

**Closed by binji** 2019-09-25 20:25 UTC
